In [47]:
## Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a2=a.reshape(2,5)
a2


[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
## Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
ar=np.arange(1,21)
b=ar[5:15]
print(b)

[ 6  7  8  9 10 11 12 13 14 15]


In [46]:
##Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears'
 ##and the value 4. 

import pandas as pd
s=pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
s['pears']=4
print(s)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [53]:
## Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
d=[
    ["Anu",23,"F"],
    ["Manu",30,"M"],
    ["Tanu",20,"F"],
    ["Jack",23,"M"],
    ["marry",30,"F"],
    ["Jeena",30,"F"],
    ["liya",30,"f"],
    ["John",31,"M"],
    ["Ethen",24,"M"],
    ["Meena",25,"F"]
]
df=pd.DataFrame(d,columns=["Name","Age","gender"])
print(df)


    Name  Age gender
0    Anu   23      F
1   Manu   30      M
2   Tanu   20      F
3   Jack   23      M
4  marry   30      F
5  Jeena   30      F
6   liya   30      f
7   John   31      M
8  Ethen   24      M
9  Meena   25      F


In [60]:
## Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst,
#. corresponding to the rows in the  dataframe

df['Occupation']=['Programmer','Manager','Analyst','Programmer','Manager','Analyst','Programmer','Manager','Analyst','manager']
df

Name  Age gender  Occupation
0    Anu   23      F  Programmer
1   Manu   30      M     Manager
2   Tanu   20      F     Analyst
3   Jack   23      M  Programmer
4  marry   30      F     Manager
5  Jeena   30      F     Analyst
6   liya   30      f  Programmer
7   John   31      M     Manager
8  Ethen   24      M     Analyst
9  Meena   25      F     manager

In [70]:
### Select the rows of the dataframe where the age is greater than or equal to 30.
s=df[df['Age']>=30]
s

Name  Age gender  Occupation
1   Manu   30      M     Manager
4  marry   30      F     Manager
5  Jeena   30      F     Analyst
6   liya   30      f  Programmer
7   John   31      M     Manager

In [87]:
## Convert this dataframe to a csv file and read that csv file, finally display the contents.
 # convert to csv
df.to_csv("DataFrameExample.csv")

# Reading csv file
r=pd.read_csv("DataFrameExample.csv")


# printin g csv file
print(r)


   Unnamed: 0   Name  Age gender  Occupation
0           0    Anu   23      F  Programmer
1           1   Manu   30      M     Manager
2           2   Tanu   20      F     Analyst
3           3   Jack   23      M  Programmer
4           4  marry   30      F     Manager
5           5  Jeena   30      F     Analyst
6           6   liya   30      f  Programmer
7           7   John   31      M     Manager
8           8  Ethen   24      M     Analyst
9           9  Meena   25      F     manager
